backend:
  name: github
  repo: earner-ai/earner-cms
  branch: master
  open_authoring: true
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  # - name: 'config'
  #   label: 'Config'
  #   delete: false
  #   editor:
  #     preview: false
  #   files:
  #     - name: 'general'
  #       label: 'Site Config'
  #       file: 'config.json'
  #       description: 'General site settings'
  #       fields:
  #         - label: 'URL'
  #           name: 'base_url'
  #           widget: 'string'
  #           hint: 'Do not enter the trailing slash of the URL'
  #         - label: 'Site title'
  #           name: 'site_title'
  #           widget: 'string'
  #         - label: 'Site description'
  #           name: 'site_description'
  #           widget: 'string'
  #         - label: 'Site keywords'
  #           name: 'site_keywords'
  #           widget: 'list'
  #           summary: '{{fields.keyword.keyword}}'
  #           field:
  #             label: Keyword
  #             name: keyword
  #             widget: 'string'
  #         - label: 'Twitter account'
  #           name: 'twitter_account'
  #           widget: 'string'
  #         - label: 'GitHub account'
  #           name: 'github_account'
  #           widget: 'string'

  - name: 'meta'
    label: 'Meta'
    delete: false
    editor:
      preview: false
    files:
      - name: 'authors'
        label: 'Authors'
        file: 'meta/authors.yml'
        description: 'Author descriptions'
        fields:
          - name: authors
            label: Authors
            label_singular: 'Author'
            widget: list
            fields:
              - label: 'Slug'
                name: 'slug'
                widget: 'string'
                hint: 'The part of a URL identifies the author'
              - label: 'Name'
                name: 'name'
                widget: 'string'
                hint: 'First and Last'
              - label: 'Introduction'
                name: 'introduction'
                widget: 'text'
      - name: 'tags'
        label: 'Tags'
        file: 'meta/tags.yml'
        description: 'List of tags'
        fields:
          - name: tags
            label: Tags
            label_singular: 'Tag'
            widget: list
            fields:
              - label: 'Slug'
                name: 'slug'
                widget: 'string'
                hint: 'The part of a URL identifies the tag'
              - label: 'Display Name'
                name: 'name'
                widget: 'string'
                hint: 'Tag name for displaying on the site'

  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog/'
    extension: 'mdx'
    format: 'frontmatter'
    create: true
    slug: '{{title}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      # - label: 'Slug'
      #   name: 'slug'
      #   widget: 'hidden'
      #   default: title.title
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        dateFormat: 'YYYY-MM-DD'
        timeFormat: false
      - label: Author
        name: 'author'
        widget: relation
        collection: 'meta'
        file: 'authors'
        searchFields:
          - 'authors.*.name'
        displayFields:
          - 'authors.*.name'
        valueField: 'authors.*.slug'
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        summary: '{{fields.tag.tag}}'
        field:
          label: Tag
          name: tag
          widget: 'string'
      - label: 'Brief Summary'
        name: 'summary'
        widget: 'markdown'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  - name: 'helpful info'
    label: 'Helpful Info'
    folder: 'content/helpful-info/'
    extension: 'mdx'
    format: 'frontmatter'
    create: true
    slug: '{{title}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      # - label: 'Slug'
      #   name: 'slug'
      #   widget: 'hidden'
      #   default: title.title
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        dateFormat: 'YYYY-MM-DD'
        timeFormat: false
      - label: 'Sources'
        name: 'sources'
        widget: 'list'
        summary: '{{fields.source.source}}'
        field:
          - label: Source name
            name: sourceName
            widget: 'string'
          - label: Link
            name: link
            widget: 'string'
      - label: Information Type
      name: 'info type'
      widget: relation
      collection: 'meta'
      file: 'helpful-info'
      searchFields:
        - 'helpful-info.*.name'
      displayFields:
        - 'helpful-info.*.name'
      valueField: 'helpful-info.*.slug'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
